swagger: '2.0'
info:
  version: '1.0'
  title: Global Miles POS API
  description: "By integrating GlobalMiles POS APIs, Merchants can offer to the GlobalMiles users  earn mile and shop with their miles in their in-stores.\n\nWork Flow:\nCommon to dos both for Earn/Pay with miles. \n\nWe will provide Client ID/ Secret Key. Ask us Please.\nBefore using any APIS of us, you need to authorise by using your Client ID / Secret Key  to get access_token.  \nDuring shopping cashier ask GlobalMiles user  for  GSM No or QR code and enter into POS. \nPOS software Post this info to GlobalMiles Server by using the API  GetCustomerInfo and get uniq identifier in order to  use at TransactionResult API  if you follow EarnMiles work Flow or  use at  StartBonusPayment API if you follow Use your Miles work flow. \n\nEarn Mile: \nAfter Getting Customer Info, Cashier will finalise the payment, as the payment done at POS post TransactionResult .\n\nUse Your Mile(Bonus):\n\nAfter Getting Customer Info, As all the items added to basket, Cashier ask for the payment method as the Globalmiles selected as payment method, Pos software Post this info GlobalMiles Server by using the API  StartBonusPayment .\n\nAn OTP code is send to the Customer mobile phone. The Customer/cashier enter this OTP into POS and this info Post to Globalmiles server by the BonusComplete API.\n\nCancel Payment with Miles:\nBy using Get Bonus Provision & CancelBonusPayment APIs  it allows to  list related sale on the POS and Cancel it ."
host: default
basePath: /
securityDefinitions:
  auth:
    type: oauth2
    flow: application
    tokenUrl: https://api.sandbox.globalmiles.com/oauth/token
    scopes: {}
    x-skip-client-authentication: false
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /v1/pos/TransactionResult:
    post:
      description: >-
        After getting customer info by Get customer Info API and finished the shopping procedure in POS terminal, use this API to complete transaction.


        You can try this API with configuring client parameters in Console Tab below. Test OAuthClientId is 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66

        and OAuthClientSecret is d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      summary: Transaction Result
      tags:
      - Payment Systems
      operationId: V1PosTransactionResultPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/TransactionResultRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/TransactionResultResponse'
          examples:
            application/json:
              returnCode: 0
              returnDesc: ''
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /oauth/token:
    post:
      description: 'An access token will allow you to make requests for the system. We support only one type of token: client_credentials'
      summary: Authentication
      tags:
      - Authentication
      operationId: OauthTokenPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/OAuthRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/OAuthResponse'
          examples:
            application/json:
              access_token: 4a703ba19309b6197670e0606574cbe003bad856003fa36d31bce9a01b6b114c
              token_type: bearer
              created_at: 1496737098
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/pos/GetCustomerInfo:
    post:
      description: >-
        This API will help you to retrieve customer's mil quantity and unique identifier value.Unique identifier value must be used by Transaction Result API in order to complete shopping.


        You can try this API with configuring client parameters in Console Tab below. Test OAuthClientId is 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66

        and OAuthClientSecret is d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      summary: Get Customer Info
      tags:
      - Common
      operationId: V1PosGetCustomerInfoPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/GetCustomerInfoRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/GetCustomerInfoResponse'
          examples:
            application/json:
              returnCode: 0
              returnDesc: ''
              recognitionId: 197
              availablePoint: 350
              loyaltyDiscountedPrice: 1000
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/pos/StartBonusPayment:
    post:
      description: >-
        After getting customer info's and RecognitionID to start Payment with Miles Use this API.

        After calling this API successfully OTP code send to customer GSM number. This OTP must be used with Complete API in order to complete sale.


        You can try this API with configuring client parameters in Console Tab below. Test OAuthClientId is 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66

        and OAuthClientSecret is d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      summary: Start Bonus Payment
      tags:
      - Bonus Payments
      operationId: V1PosStartBonusPaymentPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/StartBonusPaymentRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/StartBonusPaymentResponse'
          examples:
            application/json:
              returnCode: 0
              returnDesc: ''
              bonusPaymentProvisionId: 205
              OTPNeeded: true
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/pos/CompleteBonusPayment:
    post:
      description: >-
        In order to finalize payment with Miles use this API. Use the OTP number  which is send to user GSM on the Request body.


        You can try this API with configuring client parameters in Console Tab below. Test OAuthClientId is 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66

        and OAuthClientSecret is d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      summary: Complete Bonus Payment
      tags:
      - Bonus Payments
      operationId: V1PosCompleteBonusPaymentPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/CompleteBonusPaymentRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/CompleteBonusPaymentResponse'
          examples:
            application/json:
              returnCode: 0
              returnDesc: ''
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/pos/CancelBonusPayment:
    post:
      description: >-
        In order to cancel payment with miles you can use this API. It allows to cancel payment only related GSM and terminal ID numbers.


        You can try this API with configuring client parameters in Console Tab below. Test OAuthClientId is 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66

        and OAuthClientSecret is d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      summary: Cancel Bonus Payment
      tags:
      - Bonus Payments
      operationId: V1PosCancelBonusPaymentPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/CancelBonusPaymentRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/CancelBonusPaymentResponse'
          examples:
            application/json:
              returnCode: 0
              returnDesc: ''
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /v1/pos/GetBonusProvisions:
    post:
      description: >-
        Before cancelling the payment with Miles this API is used to list the related sale.


        You can try this API with configuring client parameters in Console Tab below. Test OAuthClientId is 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66

        and OAuthClientSecret is d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      summary: Get Bonus Provisions
      tags:
      - Bonus Payments
      operationId: V1PosGetBonusProvisionsPost
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: The body of the request.
        schema:
          $ref: '#/definitions/GetBonusProvisionsRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/GetBonusProvisionsResponse'
          examples: {}
        400:
          description: Bad Request	- The request was unacceptable, often due to missing a required parameter.
          schema: {}
        401:
          description: Unauthorized - No valid API key provided.
          schema: {}
        402:
          description: Request Failed - The parameters were valid but the request failed.
          schema: {}
        404:
          description: Not Found - The requested resource doesn't exist.
          schema: {}
        429:
          description: Too Many Requests - Too many requests hit the API too quickly.
          schema: {}
        default:
          description: Server Error - Something went wrong.
          schema: {}
      security:
      - auth: []
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
definitions:
  CompleteBonusPaymentResponse:
    title: CompleteBonusPaymentResponse
    example:
      returnCode: 0
      returnDesc: ''
    type: object
    properties:
      returnCode:
        description: 0  Success, 1 and bigger than 1 unsuccessful
        example: 0
        type: integer
        format: int32
      returnDesc:
        description: if success return is empty. if unsuccessful it returns error message
        example: '""'
        type: string
    required:
    - returnCode
    - returnDesc
  CancelBonusPaymentResponse:
    title: CancelBonusPaymentResponse
    example:
      returnCode: 0
      returnDesc: ''
    type: object
    properties:
      returnCode:
        description: 0  Success, 1 and bigger than 1 unsuccessful
        example: 0
        type: integer
        format: int32
      returnDesc:
        description: if success return is empty. if unsuccessful it returns error message
        example: '""'
        type: string
    required:
    - returnCode
    - returnDesc
  GetBonusProvisionsRequest:
    title: GetBonusProvisionsRequest
    description: ''
    example:
      readCode: 5929000000
      readCodeType: 1
      OKCSicilNo: JH20085055
    type: object
    properties:
      readCode:
        description: Müşteri tanıma tercihi, Telefon numarası, QR code gibi
        example: '"5929000000"'
        type: string
      readCodeType:
        description: '1: Telefon numarası, 2: Müşteri unique identifier, 3: Diğer'
        example: '"1"'
        type: string
      OKCSicilNo:
        description: Terminal code.
        example: '"JH20085055"'
        type: string
    required:
    - readCode
    - readCodeType
    - OKCSicilNo
  GetBonusProvisionsResponse:
    title: GetBonusProvisionsResponse
    type: object
    properties:
      returnCode:
        description: 0  Success, 1 and bigger than 1 unsuccessful
        type: integer
        format: int32
      returnDesc:
        description: if success return is empty. if unsuccessful it returns error message
        type: string
      bonusProvisions:
        type: array
        items:
          $ref: '#/definitions/BonusProvision'
    required:
    - returnCode
    - returnDesc
    - bonusProvisions
  BonusProvision:
    title: BonusProvision
    type: object
    properties:
      bonusPaymentProvisionId:
        description: Provision ID
        type: string
      usedBonusAmount:
        description: Used Bonus Amount
        type: integer
        format: int32
      dateTime:
        description: Date/time
        type: string
    required:
    - bonusPaymentProvisionId
    - usedBonusAmount
    - dateTime
  OAuthRequest:
    title: OAuthRequest
    description: Representing an OAuth request.
    example:
      client_id: 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66
      client_secret: d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
      grant_type: client_credentials
    type: object
    properties:
      client_id:
        description: ID of the client which is provided by Global Miles.
        example: 552698b91cae424b9b3ddee14eea6faf564f1b5fb7764854b73b2763e0e68c66
        type: string
      client_secret:
        description: Secret of the client which is provided by Global Miles.
        example: d0a8b00a3d754ea5a013465bcc23f6efa89e9dfb080a4f4eb460e3306653d92b
        type: string
      grant_type:
        description: 'Type of the OAuth flows. We support only one type of token: client_credentials'
        example: client_credentials
        type: string
    required:
    - client_id
    - client_secret
    - grant_type
  OAuthResponse:
    title: OAuthResponse
    description: Representing an OAuth response.
    example:
      access_token: '{{access_token}}'
      token_type: bearer
      created_at: 1496737098
    type: object
    properties:
      access_token:
        description: An access token from the authorization server.
        example: '{{access_token}}'
        type: string
      token_type:
        description: The type of token this is, typically just the string "bearer".
        example: bearer
        type: string
      created_at:
        description: The time in unix time format when the access token was created.
        example: 1496737098
        type: string
    required:
    - access_token
    - token_type
    - created_at
  TransactionResultRequest:
    title: TransactionResultRequest
    example:
      totalReceiptAmount: 2000
      totalVATAmount: 1000
      OKCSicilNo: JH20085055
      ReceiptNo: 0007
      Zno: 15
      EkuNo: 03
      recognitionId: 197
      ReceiptType: 1
      ReceiptDateTime: 150420171530
      InvoiceInfo:
        invoiceType: 0
        invoiceNo: 17
        invoiceDate: 15.04.2017
      Payments:
      - payAmount: 2000
        paymentType: 1
      Discounts:
      - orijin: ''
        type: ''
        value: ''
    type: object
    properties:
      totalReceiptAmount:
        description: Total Receipt Amount  ex:12.35 TL == 1235
        type: integer
        format: int32
      totalVATAmount:
        description: 'Total VAT Amount  ex: 0.85 TL == 85'
        type: integer
        format: int32
      OKCSicilNo:
        description: Terminal code.
        type: string
      ReceiptNo:
        description: ReceiptNo
        type: integer
        format: int32
      Zno:
        description: Z no
        type: integer
        format: int32
      recognitionId:
        description: Session based Identification Number .
        type: integer
        format: int32
      EkuNo:
        description: Eku no (Electronic Journal)
        type: integer
        format: int32
      ReceiptType:
        description: Receipt Type (Invoice , Food ..)
        type: string
      ReceiptDateTime:
        description: It should be  GGAAYYYYSSDD formatted.
        type: string
      InvoiceInfo:
        $ref: '#/definitions/Invoice'
      Payments:
        description: Payment Detail Block
        example:
        - payAmount: 2000
          paymentType: 1
        type: array
        items:
          $ref: '#/definitions/Payment'
      Discounts:
        description: ''
        example:
        - orijin: ''
          type: ''
          value: ''
        type: array
        items:
          $ref: '#/definitions/Discount'
    required:
    - totalReceiptAmount
    - totalVATAmount
    - OKCSicilNo
    - ReceiptNo
    - Zno
    - recognitionId
    - EkuNo
    - ReceiptType
    - ReceiptDateTime
    - InvoiceInfo
    - Payments
    - Discounts
  StartBonusPaymentRequest:
    title: StartBonusPaymentRequest
    example:
      totalReceiptAmount: 600
      usedBonusAmount: 300
      recognitionId: 8
      OKCSicilNo: ABCDEFG123
    type: object
    properties:
      totalReceiptAmount:
        description: Total Receipt Amount  ex:12.35 TL == 1235
        example: 300
        type: integer
        format: int32
      usedBonusAmount:
        description: Used Bonus(Mile) Amount that has been used in the shopping  ex:0.85 TL == 85
        example: 600
        type: integer
        format: int32
      recognitionId:
        description: Session based user identification number
        example: 8
        type: integer
        format: int32
      OKCSicilNo:
        description: Terminal code.
        example: 8
        type: string
    required:
    - totalReceiptAmount
    - usedBonusAmount
    - recognitionId
    - OKCSicilNo
  CancelBonusPaymentRequest:
    title: CancelBonusPaymentRequest
    example:
      bonusPaymentProvisionId: 206
      OKCSicilNo: JH20085055
    type: object
    properties:
      bonusPaymentProvisionId:
        description: Provision ID
        example: '"206"'
        type: string
      OKCSicilNo:
        description: Terminal code.
        example: '"JH20085055"'
        type: string
    required:
    - bonusPaymentProvisionId
    - OKCSicilNo
  GetCustomerInfoResponse:
    title: GetCustomerInfoResponse
    example:
      returnCode: 0
      returnDesc: ''
      recognitionId: 860444800
      availablePoint: 0
      loyaltyDiscountedPrice: 9000
    type: object
    properties:
      returnCode:
        description: 0 ise başarılı, 1 veya daha büyük ise başarısız
        example: 0
        type: integer
        format: int32
      returnDesc:
        description: Başarılı ise boş, eğer hata varsa; hata mesajını içerir.
        type: string
      recognitionId:
        description: Kullanıcının GlobalMiles sistemindeki unique identifier değeri
        example: 860444800
        type: integer
        format: int32
      availablePoint:
        description: 'Müşterinin bu işlemde kullanabileceği puanın TL karşılığıdır. Son iki karakter kuruşları temsil eder. Örneğin: 12.56 TL == 1256'
        example: 0
        type: integer
        format: int32
      loyaltyDiscountedPrice:
        description: 'Sadakat indirimi. Son iki karakter kuruşları temsil eder. Örneğin: 90.50 TL == 9050'
        example: 9000
        type: integer
        format: int32
    required:
    - returnCode
    - returnDesc
    - recognitionId
    - availablePoint
    - loyaltyDiscountedPrice
  GetCustomerInfoRequest:
    title: GetCustomerInfoRequest
    example:
      readCode: 5929000000
      readCodeType: 1
      totalAmount: 10000
      totalVATAmount: 1000
      OKCSicilNo: JH20085055
    type: object
    properties:
      readCode:
        description: Customer Identification Method ; GSM NO, Customer Unique ID or CODE
        example: '"5929000000"'
        type: string
      readCodeType:
        description: '1: GSM NO, 2: Customer unique identifier, 3: CODE'
        example: 1
        type: integer
        format: int32
      totalAmount:
        description: Total receipt amount.  ex:12.34 TL == 1234
        example: 10000
        type: integer
        format: int32
      totalVATAmount:
        description: Total Tax Value. EX:1.34 TL == 134
        example: 1000
        type: integer
        format: int32
      OKCSicilNo:
        description: Terminal code.
        example: '"JH20085055"'
        type: string
    required:
    - readCode
    - readCodeType
    - totalAmount
    - totalVATAmount
    - OKCSicilNo
  Discount:
    title: Discount
    example:
      orijin: ''
      type: ''
      value: ''
    type: object
    properties:
      orijin:
        type: string
      type:
        type: string
      value:
        type: string
    required:
    - orijin
    - type
    - value
  Payment:
    title: Payment
    example:
      payAmount: 2000
      paymentType: 1
    type: object
    properties:
      payAmount:
        example: 2000
        type: integer
        format: int32
      paymentType:
        example: 1
        type: integer
        format: int32
    required:
    - payAmount
    - paymentType
  Invoice:
    title: Invoice
    example:
      invoiceType: 0
      invoiceNo: 17
      invoiceDate: 15.04.2017
    type: object
    properties:
      invoiceType:
        example: 0
        type: string
      invoiceNo:
        description: ''
        example: 17
        type: string
      invoiceDate:
        example: 15.04.2017
        type: string
    required:
    - invoiceType
    - invoiceNo
    - invoiceDate
  TransactionResultResponse:
    title: TransactionResultResponse
    example:
      returnCode: 0
      returnDesc: ''
    type: object
    properties:
      returnCode:
        description: 0 ise başarılı, 1 veya daha büyük ise başarısız
        type: integer
        format: int32
      returnDesc:
        description: Başarılı ise boş, eğer hata varsa; hata mesajını içerir.
        type: string
    required:
    - returnCode
    - returnDesc
  StartBonusPaymentResponse:
    title: StartBonusPaymentResponse
    example:
      returnCode: 0
      returnDesc: ''
      bonusPaymentProvisionId: 4
      OTPNeeded: true
    type: object
    properties:
      returnCode:
        description: 0 ise başarılı, 1 veya daha büyük ise başarısız
        example: 0
        type: integer
        format: int32
      returnDesc:
        description: Başarılı ise boş, eğer hata varsa; hata mesajını içerir.
        type: string
      bonusPaymentProvisionId:
        description: Provizyon ID
        example: '"4"'
        type: string
      OTPNeeded:
        description: Tek kullanımlık parola gerekli mi?
        example: true
        type: boolean
    required:
    - returnCode
    - returnDesc
    - bonusPaymentProvisionId
    - OTPNeeded
  CompleteBonusPaymentRequest:
    title: CompleteBonusPaymentRequest
    example:
      bonusPaymentProvisionId: 206
      OKCSicilNo: JH20085055
      OTP: 3636
    type: object
    properties:
      bonusPaymentProvisionId:
        description: Provision ID
        example: '"206"'
        type: string
      OKCSicilNo:
        description: Terminal code.
        example: '"JH20085055"'
        type: string
      OTP:
        description: One time password that sends to customer phone
        example: '"3636"'
        type: string
    required:
    - bonusPaymentProvisionId
    - OKCSicilNo
    - OTP
